# Generated by Django 3.2.3 on 2021-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('quiz_id', models.IntegerField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date answered')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
