# Generated by Django 3.2.3 on 2021-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210602_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
