# Generated by Django 3.2.3 on 2021-06-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_answers_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answers',
        ),
    ]
