# Generated by Django 3.2.3 on 2021-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
