# Generated by Django 3.2.3 on 2021-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_questions_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('quiz_id', models.IntegerField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date answered')),
                ('user', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
