# Generated by Django 3.2.3 on 2021-06-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_user_course_user_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='Courses',
        ),
    ]
